fix: add missing poetry dependency (#1771)
This commit fixes the following error when trying to export a
course:

> ./scripts/exportYamlCourse.sh spanish-from-english
> ⏳ Exporting course spanish-from-englishTraceback (most recent call last):
>  File "librelingo_json_export/cli.py", line 5, in <module>
>    from librelingo_json_export.export import export_course
> ModuleNotFoundError: No module named 'librelingo_json_export'